### ISSUE TITLE
Using with cmake and Qt5

### ISSUE THREAD

**Issue by buelowp** [emqx/qmqtt#178]
I have been using this with qmake and it works well. However, I have a cmake C++ Qt5 based project which caused me some issues. Using the following almost works, but needs a change to fix completely.
````
find_package(Qt5 COMPONENTS Core Sql qmqtt REQUIRED)
target_link_libraries(${PROJECT_NAME} ${Qt5Core_LIBRARIES} ${Qt5Sql_LIBRARIES} ${Qt5qmqtt_LIBRARIES})
````

However, it needs to find the libary libQt5qmqtt.so.1.0.0, which isn't installed by the qmqtt build system. At least on ubuntu, the find cmake module searches for the prefix Qt5 for all libraries and can't find just liqmqtt.so.1.0.0 without a lot of extra logic which kind of breaks find_package usage.

I would ask for one of two things. Either tell me how to use cmake more correctly (have you dealt with this differently), or can you add an installer change to create a symlink from libqmqtt.so.1.0.0 to libQt5qmqtt.so.1.0.0 in the target lib directory?

Thank you.

**Comment by mwallnoefer** [comment]
@Psy-Kai @KonstantinRitt Any idea?

**Comment by mwallnoefer** [comment]
@ejvr Do you have any idea? I am not so comfortable with the build.

**Comment by ejvr** [comment]
I'm not an expert of qmake either, but it seems that the cmake files generated by the build refer to the qmqtt library as libQt5qmqtt.so.*. However, the library itself has is called libqmqtt.so.*. 

We can fix this with 2 changes:
* Change the target name in src/mqtt/qmqtt.pro from qmqtt to QtQmqtt
* Apply the same change in sync.profile.

That appears to fix the problem, at least on my debian system. However, this changes the name of the shared library created by the build system. That could case problems in existing setups. 

Maybe @buelowp can test the change? If it works I'm prepared to create a pull request for this fix.

**Comment by buelowp** [comment]
I'd be happy to test this, do you have a patch or branch?

**Comment by ejvr** [comment]
Just created a branch. You can find it [here](https://github.com/ejvr/qmqtt/tree/emqtt).

**Comment by buelowp** [comment]
Thank you, that built and installed on both X86 and arm architectures. I can now link using cmake with the following 

```
find_package(Qt5 COMPONENTS Core Sql Qmqtt REQUIRED)
```

Thank you.

**Comment by ejvr** [comment]
Just created a pull request. Note that I changed the qmake configuration only.

**Comment by buelowp** [comment]
Thanks everyone.
