### ISSUE TITLE
MQTT v5 request/reply pattern

### ISSUE THREAD

**Issue by ncg81** [emqx/qmqtt#188]
Hello you guys.

Thank you for writing a Qt native client for EMQX.

To my knowledge the **EMQX Broker** supports **MQTT v5**  which in turn supports the **request/reply** pattern. However, by quickly glancing at **qmqtt**'s method signatures, it appears that this client does not handle **request/reply** scenarios. I was expecting to find a slot like: 

`quint16 request(const QString& requestTopic, const QString& replyTopic, const quint8 qos);`

and afferent signals.

Are there any plans for supporting the **request/reply** pattern in **qmqtt** ?

**Comment by mwallnoefer** [comment]
Nope, the decision was to maintain **qmqtt** with the current feature set to support Mqtt release 3.1.1. All new features should be proposed to Qt's integrated mqtt library: https://doc.qt.io/QtMQTT/index.html.
