### ISSUE TITLE
connect to server success,then call connectionState interface,the return value is STATE_INIT.

### ISSUE THREAD

**Issue by hya1711** [emqx/qmqtt#199]
connect to server success,then call connectionState interface,the return value is STATE_INIT.

**Comment by ejvr** [comment]
A quick glance at the code shows that the connection state is a member of ClientPrivate which initializes it to STATE_INIT, and never changes it again.

>

So as far as I can see the property is useless right now.

**Comment by mwallnoefer** [comment]
Correct, fortunately it was not that hard to fix it :laughing: : 50382ef96fadbfddb48fb177fbf32b6382b1509e
