### ISSUE TITLE
Compile error with Qt5.7 on CentOS7 platform

### ISSUE THREAD

**Issue by BarleyXu** [emqx/qmqtt#201]
When I compile the program with qt5.7. Some errors occured such as follow:

.moc/moc_qmqtt_ssl_socket_p.cpp:55:6: error: ‘QMQTT’ has not been declared
 void QMQTT::SslSocket::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)

**Comment by mwallnoefer** [comment]
Hi BarleyXu,

you should provide us with a more complete build log, if possible containing also the build config variables. Otherwise we are not able to help you...
