### ISSUE TITLE
How to use domain name connection

### ISSUE THREAD

**Issue by czqinyes** [emqx/qmqtt#202]
OK：
QMQTT::Client *client = new QMQTT::Client();
QHostAddress host(‘127.0.0.1’);
client->setHost(host);
client->setPort(1883);
client->setClientId("clientId");
client->setUsername("user");
client->setPassword("password");
client->connectToHost();

Error:
QMQTT::Client *client = new QMQTT::Client();
QHostAddress host(‘www.test.com’);
client->setHost(host);
client->setPort(1883);
client->setClientId("clientId");
client->setUsername("user");
client->setPassword("password");
client->connectToHost();

question: why can't I use the domain name connection?

**Comment by mwallnoefer** [comment]
Please refer to the Qt documentation, this is out of our scope: https://doc.qt.io/qt-5/qhostaddress.html. This is the helper class to do DNS lookups: https://doc.qt.io/qt-5/qhostinfo.html

**Comment by ejvr** [comment]
QHostAddress is a wrapper around an IP-address it does not do DNS lookups.

If you want to use a hostname to connect, you should use one of the client constructors that receive a hostName QString.
