### ISSUE TITLE
Newbie Installation

### ISSUE THREAD

**Issue by pabloleibo** [emqx/qmqtt#205]
Hi, I'm trying to compile this code to use it in my application. I'm a newbie with Qt, and I can't achieve this goal.
I downloaded the entire repository and open the top level qmqtt.pro. 
When I open it, I select MinGW for 32 and 64 bits as compilers, and then build the project.
The first problem is that the examples folder doesn't compile. Qt throws an error saying that qmqtt is not found as a module first, and then that qmqtt.h is not found.
A dll file is generated, but I can't use it in my code. If I try to include the qmqtt.h of the src file in my code, I have finally to include the entire src in my project, but it also doesn't work.
Can you help me with the steps I have to do to compile this module and use it in my code? 
Thanks and sorry for my inexperience!

**Comment by mwallnoefer** [comment]
According to the bug description you are working on Windows (*"MinGW"*) which is a bit special what regards to Qt modules. I used to work with *qmqtt* on Windows but that was some years ago, where it still was a plain Qt library (DLL) and not a module.

Let's ask @ejvr or @KonstantinRitt, maybe they're more expert here...

**Comment by KonstantinRitt** [comment]
in you .pro file:
CONFIG += qmqtt # (or how the module is named these days?)

**Comment by pabloleibo** [comment]
Hi! thanks for your response!
Yes, I included it after building the source code of this repo and installing it. The matter is that including qmqtt in config doesn't work. The QMQTT class is not recognized.
Which .h file has to be included? Because the qmqtt.h file of src folder requires others headers files?

**Comment by ejvr** [comment]
If you have build the qmqtt you should install it first before trying to build code that uses it. In QT creation you can do that with Build -> Deploy Project. This step should copy the headers files to your QT installation directory (iirc, they will be put inside a qmqtt or mqtt folder there). It will also copy the library files.
If you have performed the deployment step, you could check if the qmqtt header files are present in the QT installation (qmqtt.h should be one of them).
