### ISSUE TITLE
wss onNetworkDisconnected

### ISSUE THREAD

**Issue by czqinyes** [emqx/qmqtt#215]
Let's move on to #212, failure to connect to WSS is the MQTT version issue(mqttClient->setVersion(QMQTT::MQTTVersion::V3_1_1);).
 But a new problem arose, connected, disconnect all the time, unsteadiness.
If possible, I will email the test domain to you for testing.
Please send me an email. Thank you very much

**Comment by ejvr** [comment]
I don't understand what you mean here. Is using MQTT V3.1.1 causing issues? Are those issues different from using the default version? How often do these disconnects occur? Do you have normal communication when connected? If you have access to the mqtt broker, you could check out the server logs.

To get some more insight into the issue, maybe you can try to use your code with a public mqtt service. For example this one: [https://www.emqx.io/mqtt/public-mqtt5-broker](https://www.emqx.io/mqtt/public-mqtt5-broker). I've tested the example project on this one using SSL and websockets. Note that on this server you cannot subscribe to all topics (topic filter '#'). The filter needs to start with a known topic segment. So 'blah/#' should work.

**Comment by czqinyes** [comment]
This is my open function:
`void MyMQTT::openMQTT(MQTTStruct mqtt)
{
	if (m_mqttClient == NULL)
	{
		qRegisterMetaType<QMQTT::ClientError>("QMQTT::ClientError");
		qRegisterMetaType<QMQTT::Message>("QMQTT::Message");
		qRegisterMetaType<QList<QSslError>>("const QList<QSslError>");

		if (!mqtt.wss)
		{
			m_mqttClient = new QMQTT::Client;
		}
		else
		{
			m_mqttClient = new QMQTT::Client(mqtt.ip, "<origin>", QWebSocketProtocol::VersionLatest);
		}

		connect(m_mqttClient, &QMQTT::Client::connected, this, &MyMQTT::slot_conncted);
		connect(m_mqttClient, &QMQTT::Client::disconnected, this, &MyMQTT::slot_disconnected);
		connect(m_mqttClient, &QMQTT::Client::error, this, &MyMQTT::slot_error);
		connect(m_mqttClient, &QMQTT::Client::sslErrors, this, &MyMQTT::slot_sslErrors);
		connect(m_mqttClient, &QMQTT::Client::subscribed, this, &MyMQTT::slot_subscribed);
		connect(m_mqttClient, &QMQTT::Client::unsubscribed, this, &MyMQTT::slot_unsubscribed);
		connect(m_mqttClient, &QMQTT::Client::received, this, &MyMQTT::signal_receivedMQTTMsg);
	}
	if (m_mqttClient)
	{
		if (m_mqttClient->isConnectedToHost())
		{
			m_mqttClient->disconnectFromHost();
		}
		m_mqttMsg = mqtt;	
		 
		QHostAddress host(mqtt.ip); 
		
		if (!mqtt.clientId.isEmpty())
			m_mqttClient->setClientId(mqtt.clientId);
		else
			m_mqttClient->setClientId(QDateTime::currentDateTime().toString("yyyyMMddhhmmsszzz"));
		if (!mqtt.wss)
		{
			m_mqttClient->setHost(host);
			//m_mqttClient->setPort(mqtt.port);
		}
		m_mqttClient->setPort(mqtt.port);
		if (!mqtt.userName.isEmpty() || !mqtt.password.isEmpty())
		{
			m_mqttClient->setUsername(mqtt.userName);
			m_mqttClient->setPassword(mqtt.password.toLocal8Bit());
		}
		m_mqttClient->setVersion(QMQTT::MQTTVersion::V3_1_1);
		//m_mqttClient->setKeepAlive(10);
		m_mqttClient->setAutoReconnect(true);
		m_mqttClient->setAutoReconnectInterval(1000);
		m_mqttClient->setCleanSession(true);
		m_mqttClient->connectToHost();
	}
}`
I have received "SocketRemoteHostClosedError".Here's my demo.
[https://github.com/czqinyes/wssTest](url)
You can fill in the information at wssTest.cpp line 27 to 31;
Thanks.

**Comment by ejvr** [comment]
The trick is to use the right QMQTT::Client constructor for each connection type.
Also make sure you pass the right arguments. For example when creation a websocket based client, you should pass an URL as the first argument (and not a IP-address). Do not use the setHost and setPort functions.They may work for plain tcp and ssl connection, but probably won't work with websockets. This means that each time you enter the openMQTT function you should delete the existing Client object and create a new one,

Please take a look at he README.md file in the QMQTT project root: it contains several example on how to create Client objects based on different connection types.

**Comment by czqinyes** [comment]
I see. My program open once only.
The problem has been solved. It can be closed. Thank you

> At last I found the cause of the problem is I have not setKeepAlive, the default is 300 seconds, when I set 30 seconds is ok.
> Thanks.
