### ISSUE TITLE
can't connect server by ip?

### ISSUE THREAD

**Issue by w136111526** [emqx/qmqtt#218]
Hello, I&#039;d like to say that localhost and localhost are working on the mosquitto.exe server, and that the local Ip, or any other machine Ip, is not available, and that the server is installed locally from the mosquitto.exe website for use on windows machines. What could be the reason?
![image](https://user-images.githubusercontent.com/29495143/104163879-1279c400-5432-11eb-923c-87e8c66434c7.png)

**Comment by ejvr** [comment]
I don't understand your problem. Can you tell us what the setup is you are using?
And how is de QMQTT library involved?

**Comment by w136111526** [comment]
Thank you. I can't connect to the server because mosquitto.exe The server limits the IP address, which is not caused by qmqtt client.
