### ISSUE TITLE
Including qmqtt in pre-existing project

### ISSUE THREAD

**Issue by g-ampo** [emqx/qmqtt#222]
Hello! 

I am trying to get QMQTT to work with a pre-existing project (QGroundControl), with little success.

I am using Qt Creator in windows and got the library to build by doing the following:

1) Installed Perl (I got ActivePerl 5.28)
2) Opened Qt creator and directed to the .pro file of QMQTT, which I opened as a distinct project
3) Built the QMQTT project
4) Went to the build directory and moved the "libs" and "include " folders to QGC/libs/Qt5Qmqtt
5) Added the following snippets to QGCExternalLibs.pri:
```
INCLUDEPATH += $$BASEDIR/libs/Qt5Qmqtt/include 
LIBS += -L"$$BASEDIR/libs/Qt5Qmqtt/lib" -lQt5Qmqtt
```
Trying to `#include "qmqtt.h"` returns that no such file is found.
Addition of  `Qt += qmqtt` in QGC's .pro file only returned an error (no such module existing).
Do I need to add the built library files to the project as an external library?

Sorry if this is a newbie question, been trying to get it to work for the past 2 weeks with no sucess and I am at a loss honestly.

**Comment by ejvr** [comment]
You probably have to install qmqtt first. On the command line that would be 'make install'. To be honest I don't know how to do that in at creator.

-------- Original Message --------

**Comment by g-ampo** [comment]
Thanks for the reply. I can't use 'make install' in windows however... Does that mean I have to switch the entire project to linux?

**Comment by ejvr** [comment]
No, it must be possible to do this in windows. I'll try to find out this evening.

-------- Original Message --------

**Comment by ejvr** [comment]
In windows you can use nmake instead of make. First you start the visual studio _developer command prompt_, from there you can run `qmake`, `nmake` and `nmake install`

**Comment by g-ampo** [comment]
Thanks a lot!
