### ISSUE TITLE
Is there some additional documentation beyond the README available?

### ISSUE THREAD

**Issue by benthillerkus** [emqx/qmqtt#226]
Some concrete questions I have:
- ~~What do the `disconnect` functions do? How do they differ from `disconnectFromHost`?~~ `disconnect` and `connect` are inherited from `QObject` and refer to the signals/slot system
- Is `setHostName` just a shortcut for `setHost`?
- ~~How do the `autoReconnect` methods work?~~

Generally from the listed slots and signals on the Readme the library checks all the boxes for me and from trying it out, the API seems really good, but I'd love some written documentation or something to read into.

**Comment by ejvr** [comment]
Q: _Is there some additional documentation beyond the README available?_
A: Nope, but any help is appreciated

Q: _Is setHostName just a shortcut for setHost?_
A: No, there is a small different. The `setHost` function receives a parameter of type `QHostAddress`, which represents an IP address, but cannot represent a host name. The `setHostName` function receives a string which can represent both host name and IP address. Apart from that, they have the same purpose: identify the machine to connect with.

**Comment by benthillerkus** [comment]
Alright, I'll see if I can write some docs or contribute some examples when I'm done with the project I'm working on 😀
