### ISSUE TITLE
Connect using SSL not working when using setSslConfiguration() separately

### ISSUE THREAD

**Issue by jps05** [emqx/qmqtt#228]
Issue can be reproduced by:

QSslConfiguration sslConfig = QSslConfiguration::defaultConfiguration();
QMQTT::Client *client = new QMQTT::Client();
client->setHostName("example.com");
client->setPort(8883)
client->setSslConfiguration(sslConfig);
client->setClientId("clientId");
client->setUsername("user");
client->setPassword("password");
client->connectToHost();

Returned error: SocketRemoteHostClosedError (2)

**Comment by ejvr** [comment]
Yep, that's not going to work. To best way to create an mqtt connection over ssl is to use the constructor which takes a QSslConfiguration object as parameter. The default constructor can be used only to create a non-encrypted TCP connection.
