### ISSUE TITLE
QMQTT::Network::isConnectedToHost() is true when SSL is still negotiating

### ISSUE THREAD

**Issue by halfgaar** [emqx/qmqtt#230]
`QMQTT::Network::isConnectedToHost()` is true when SSL is still negotiating. If the client app determines actions based on that, it starts sending publish packets before the connect packet.

**Comment by ejvr** [comment]
Yep, looks like you're right. I guess we should check if `_connectionState == ConnectionState::STATE_CONNECTED` in `ClientPrivate::isConnectedToHost`.
That way, the isConnectedToHost is in sync with the 'connected' signal, which is what most developer use (I hope).

**Comment by halfgaar** [comment]
I've observed this behavior for a while in my [MqttLoadSimulator](https://github.com/halfgaar/MqttLoadSimulator) and another tool I use for debugging. It goes a bit deeper even.

My MQTT server reports publish packets before the first connect packet when clients lose their connection and reconnect. In other words, `Client::publish()` queues frames right after the SSL handshake, before it's allowed to reconnect.

I can work around it by checking a `connected` boolean I set and clear with the signals `Client::connected` and `Client::disconnected`, and only publish when it's true.

**Comment by ejvr** [comment]
That's why I proposed to check the `_connectionState`, it will be set to `STATE_CONNECTED` only if the connection acknowledgement from the broker has been received (at the same time the `Client::connected` signal is emitted). It seems to me that . I still think this would fix the issue. Maybe you can try that?

Of course, keeping a boolean using the connected and disconnected signal should also do the trick.

By the way: the client class does not check the connection state before sending frames to the broker. Apparently that has to be checked externally. That would explain receiving data in the broker right after the SSL handshake.

**Comment by mwallnoefer** [comment]
Any news here?

**Comment by halfgaar** [comment]
I'm unsure who is waiting for whom :).

I can test quick code fixes as suggested by @ejvr , but the last paragraph:

> By the way: the client class does not check the connection state before sending frames to the broker. Apparently that has to be checked externally. That would explain receiving data in the broker right after the SSL handshake.

talks a bit more about the architecture of QMQTT that I'm not authoritative on.

**Comment by ejvr** [comment]
Yeah, we got deadlocked here I guess. There was no response to my final comment, so I assumed nobody was interested in my fix. Anyway, there's now a pull request (#235) for this issue.

About my remark:

> By the way: the client class does not check the connection state before sending frames to the broker. Apparently that has to be checked externally. That would explain receiving data in the broker right after the SSL handshake.

It's a bit cryptic. What I mean is this: the Client::publish function does not do any checks on the internal connection state. It just sends a PUBLISH frame to the broker (there is a check on the socket state `Network::sendFrame`), so this could still happen during the hand shake. So apparently it's up to the user of QMQTT to make sure that this does not happen: either by tracking the connection with the `connected` and `disconnected` signals or by checking `isConnectedToHost()` before publishing.

In theory this is a bit harder to fix: if we're using QOS1 or QOS2 and we cannot send a PUBLISH frame to the broker, we probably should keep the message in memory until a connection is established.
