### ISSUE TITLE
connet server with uri

### ISSUE THREAD

**Issue by shane97luo** [emqx/qmqtt#233]
Hey, guys !  I met a problem. 

It works well when I use paho mqtt

```
string client_id_url = "*****"
mqtt::async_client_ptr  client_prt_ = std::make_shared<mqtt::async_client>("tcp://mqtt.****.com:1883",
                                                           client_id_url, 10000, persist_path.toStdString());
```

but when I try to use qmqtt replace paho, it comes wrong. I would like to know that whether qmqtt support the uri param

thanks for anwsering ! ! !

**Comment by mwallnoefer** [comment]
Sorry, I have missed your issue: we only support the connection syntaxes listed here: https://github.com/emqx/qmqtt/blob/v1.0.0/README.md. So the URI _"tcp://mqtt.****.com:1883"_ won't work against qmqtt.
