### ISSUE TITLE
Build using Qt6.5 is not possible anymore

### ISSUE THREAD

**Issue by jps05** [emqx/qmqtt#248]
As the new Qt6.5 release is missing all .prf files in Qt/6.5.0/macos/mkspecs/features folder which are used to build qmqtt like qt_parts.prf, qt_module.prf, qt_configure.prf, qt_build_config.prf, building for Qt6.5 is not possible anymore.

**Comment by ejvr** [comment]
I guess you tried to use qmake to build qmqtt. Did you also try cmake? AFAIK, CMake does not depend on the *.prf files.
