### ISSUE TITLE
CMakeLists.txt fix for Qt6

### ISSUE THREAD

**Issue by RoachLin** [emqx/qmqtt#249]
in CMakeLists.txt:

find_package( Qt5 ${qt5_min_version} COMPONENTS Core Network ${ws_component} CONFIG REQUIRED )
should change Qt5 to Qt6:
find_package( Qt6 ${qt5_min_version} COMPONENTS Core Network ${ws_component} CONFIG REQUIRED )

target_link_libraries( ${PROJECT_NAME} PUBLIC Qt5::Core Qt5::Network ${ws_libname} )
should change Qt5 to Qt6:
target_link_libraries( ${PROJECT_NAME} PUBLIC Qt6::Core Qt6::Network ${ws_libname} )

Maybe could add these changes to README to let others know how to compile on Qt6

**Comment by mwallnoefer** [comment]
Hi, thanks for the hint, I will soon add this into the README.

**Comment by RoachLin** [comment]
Thank you very much! I have no problem, you can close this issue.
