### ISSUE TITLE
Can I connect server using wss:/host:port/mqtt?

### ISSUE THREAD

**Issue by qwyinxiang** [emqx/qmqtt#257]
Can I connect mqtt server using wss,is there any examples? thank you very much.

**Comment by ejvr** [comment]
Yes, it's possible. Some time ago I wrote a small demo project which illustrates how to connect.

[You can find it here](https://github.com/ejvr/qmqtt2qml/blob/master/src/qml_qmqtt_client.cpp)

Take a look at the function `QmlQmqttClient::connectToHost()` for details on the connection.

To use websockets you have to compile `QMQTT` with websocket support (I think it's disabled by default). See `QMQTT`'s readme for  details on how to build.
